services:
  dio-manager:
    build: 
      context: .
      dockerfile: cmd/manager/Dockerfile
    ports:
      - "50051:50052" # Map Host 50051 -> Container 50052 (gRPC)
      - "8080:8080"   # HTTP Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Go to talk to Docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SCHEDULER_STRATEGY
      - NLMS_MODE

  dio-worker:
    build:
      context: .
      dockerfile: workers/python_worker/Dockerfile
    image: dio-worker # Force image name so Go Manager can find it
    environment:
      - MANAGER_ADDRESS=dio-manager:50052
      - MODEL_ID=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - WORKER_TIER=small
      - WORKER_VRAM_GB=6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  dio-worker-slow:
    build:
      context: .
      dockerfile: workers/python_worker/Dockerfile
    image: dio-worker
    environment:
      - MANAGER_ADDRESS=dio-manager:50052
      - THROTTLE_FACTOR=2.0 # Simulate 2x slower hardware for Heterogeneity Test