// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/dio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // e.g., "localhost:50051"
	Models        []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_dio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dio_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_dio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dio_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_api_proto_dio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dio_proto_rawDescGZIP(), []int{2}
}

func (x *InferenceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferenceRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	LatencyMs     float32                `protobuf:"fixed32,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_api_proto_dio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dio_proto_rawDescGZIP(), []int{3}
}

func (x *InferenceResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *InferenceResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_api_proto_dio_proto protoreflect.FileDescriptor

const file_api_proto_dio_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/dio.proto\x12\x03dio\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x10InferenceRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"J\n" +
	"\x11InferenceResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x02R\tlatencyMs2\x85\x01\n" +
	"\fOrchestrator\x12=\n" +
	"\x0eRegisterWorker\x12\x14.dio.RegisterRequest\x1a\x15.dio.RegisterResponse\x126\n" +
	"\x05Infer\x12\x15.dio.InferenceRequest\x1a\x16.dio.InferenceResponse2\x8a\x01\n" +
	"\x0fInferenceWorker\x128\n" +
	"\aPredict\x12\x15.dio.InferenceRequest\x1a\x16.dio.InferenceResponse\x12=\n" +
	"\vCheckHealth\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x1fZ\x1dgithub.com/nisaral/dio/pkg/pbb\x06proto3"

var (
	file_api_proto_dio_proto_rawDescOnce sync.Once
	file_api_proto_dio_proto_rawDescData []byte
)

func file_api_proto_dio_proto_rawDescGZIP() []byte {
	file_api_proto_dio_proto_rawDescOnce.Do(func() {
		file_api_proto_dio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dio_proto_rawDesc), len(file_api_proto_dio_proto_rawDesc)))
	})
	return file_api_proto_dio_proto_rawDescData
}

var file_api_proto_dio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_dio_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: dio.RegisterRequest
	(*RegisterResponse)(nil),  // 1: dio.RegisterResponse
	(*InferenceRequest)(nil),  // 2: dio.InferenceRequest
	(*InferenceResponse)(nil), // 3: dio.InferenceResponse
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_api_proto_dio_proto_depIdxs = []int32{
	0, // 0: dio.Orchestrator.RegisterWorker:input_type -> dio.RegisterRequest
	2, // 1: dio.Orchestrator.Infer:input_type -> dio.InferenceRequest
	2, // 2: dio.InferenceWorker.Predict:input_type -> dio.InferenceRequest
	4, // 3: dio.InferenceWorker.CheckHealth:input_type -> google.protobuf.Empty
	1, // 4: dio.Orchestrator.RegisterWorker:output_type -> dio.RegisterResponse
	3, // 5: dio.Orchestrator.Infer:output_type -> dio.InferenceResponse
	3, // 6: dio.InferenceWorker.Predict:output_type -> dio.InferenceResponse
	4, // 7: dio.InferenceWorker.CheckHealth:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_dio_proto_init() }
func file_api_proto_dio_proto_init() {
	if File_api_proto_dio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dio_proto_rawDesc), len(file_api_proto_dio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_dio_proto_goTypes,
		DependencyIndexes: file_api_proto_dio_proto_depIdxs,
		MessageInfos:      file_api_proto_dio_proto_msgTypes,
	}.Build()
	File_api_proto_dio_proto = out.File
	file_api_proto_dio_proto_goTypes = nil
	file_api_proto_dio_proto_depIdxs = nil
}
