# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/dio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/proto/dio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pi/proto/dio.proto\x12\x03\x64io\"E\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06models\x18\x03 \x03(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x10InferenceRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"7\n\x11InferenceResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\x12\n\nlatency_ms\x18\x02 \x01(\x02\x32M\n\x0cOrchestrator\x12=\n\x0eRegisterWorker\x12\x14.dio.RegisterRequest\x1a\x15.dio.RegisterResponse2K\n\x0fInferenceWorker\x12\x38\n\x07Predict\x12\x15.dio.InferenceRequest\x1a\x16.dio.InferenceResponseB\x1fZ\x1dgithub.com/nisaral/dio/pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.dio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/nisaral/dio/pkg/pb'
  _globals['_REGISTERREQUEST']._serialized_start=28
  _globals['_REGISTERREQUEST']._serialized_end=97
  _globals['_REGISTERRESPONSE']._serialized_start=99
  _globals['_REGISTERRESPONSE']._serialized_end=134
  _globals['_INFERENCEREQUEST']._serialized_start=136
  _globals['_INFERENCEREQUEST']._serialized_end=186
  _globals['_INFERENCERESPONSE']._serialized_start=188
  _globals['_INFERENCERESPONSE']._serialized_end=243
  _globals['_ORCHESTRATOR']._serialized_start=245
  _globals['_ORCHESTRATOR']._serialized_end=322
  _globals['_INFERENCEWORKER']._serialized_start=324
  _globals['_INFERENCEWORKER']._serialized_end=399
# @@protoc_insertion_point(module_scope)
